[features]
seeds = false

[programs.localnet]
slink = "Eyu3VjokBToM9jq9CE1ZuvuXBTH3v4xvSomwobHvBEqr"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run jest --detectOpenHandles --forceExit"
