[features]
seeds = false

[programs.localnet]
sbt = "XV93mE9SR2baA5b7bq2JRAj3JtMjL4Y9pMQChrBH7YB"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run jest --detectOpenHandles --forceExit"
